from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True, slots=True)
class EnvVar:
    name: str
    default: str = ""
    secret: bool = False
    production_required: bool = False
    description: str = ""


ENV_SCHEMA: Final[tuple[EnvVar, ...]] = (
    EnvVar('DISCORD_TOKEN', '', secret=True, production_required=True),
    EnvVar('DISCORD_GUILD_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_STATUS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_ANNOUNCEMENTS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_EVENTS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_AUDIT_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_SECURITY_AUDIT_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_BUSINESS_AUDIT_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_OPS_AUDIT_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_START_HERE_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_RULES_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_ROLES_AND_ACCESS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_FAQ_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_DEVLOG_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_WORLD_SIGNALS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_REPORTS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_BOT_LOGS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_STAGE_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_FORUM_SUGGESTIONS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_FORUM_BUG_REPORTS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_FORUM_GUILD_RECRUITMENT_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_FORUM_HELP_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_FORUM_LAUNCHER_AND_TECH_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_FORUM_ACCOUNT_HELP_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_FORUM_APPEALS_CHANNEL_ID', '', secret=False, production_required=False),
    EnvVar('VISITOR_ROLE_ID', '', secret=False, production_required=False),
    EnvVar('MEMBER_ROLE_ID', '', secret=False, production_required=False),
    EnvVar('GUILD_LEADER_ROLE_ID', '', secret=False, production_required=False),
    EnvVar('INTEREST_ROLE_NEWS_ID', '', secret=False, production_required=False),
    EnvVar('INTEREST_ROLE_LORE_ID', '', secret=False, production_required=False),
    EnvVar('INTEREST_ROLE_GAMEPLAY_ID', '', secret=False, production_required=False),
    EnvVar('INTEREST_ROLE_EVENTS_ID', '', secret=False, production_required=False),
    EnvVar('INTEREST_ROLE_GUILDS_ID', '', secret=False, production_required=False),
    EnvVar('INTEREST_ROLE_MEDIA_ID', '', secret=False, production_required=False),
    EnvVar('INTEREST_ROLE_DEVLOGS_ID', '', secret=False, production_required=False),
    EnvVar('DISCORD_SYNC_COMMANDS_ON_START', 'false', secret=False, production_required=False),
    EnvVar('DISCORD_STARTUP_VALIDATION_STRICT', 'true', secret=False, production_required=False),
    EnvVar('BOT_PRESENCE_TEXT', 'NeverMine | /status', secret=False, production_required=False),
    EnvVar('ALLOW_DEGRADED_WITHOUT_REDIS', 'true', secret=False, production_required=False),
    EnvVar('AUDIT_PAYLOAD_MAX_STRING_LENGTH', '256', secret=False, production_required=False),
    EnvVar('AUDIT_PAYLOAD_MAX_COLLECTION_ITEMS', '25', secret=False, production_required=False),
    EnvVar('AUDIT_PAYLOAD_MAX_DEPTH', '5', secret=False, production_required=False),
    EnvVar('AUDIT_PAYLOAD_MAX_BYTES', '8192', secret=False, production_required=False),
    EnvVar('SQLITE_OPTIMIZE_ON_CLEANUP', 'true', secret=False, production_required=False),
    EnvVar('SQLITE_ANALYZE_ON_CLEANUP', 'true', secret=False, production_required=False),
    EnvVar('SQLITE_VACUUM_MIN_INTERVAL_SECONDS', '86400', secret=False, production_required=False),
    EnvVar('NEVERMINE_SERVER_NAME', 'NeverMine', secret=False, production_required=False),
    EnvVar('NEVERMINE_SERVER_ADDRESS', 'play.nevermine.ru', secret=False, production_required=False),
    EnvVar('NEVERMINE_WEBSITE_URL', '', secret=False, production_required=False),
    EnvVar('NEVERMINE_VK_URL', '', secret=False, production_required=False),
    EnvVar('NEVERMINE_TELEGRAM_URL', '', secret=False, production_required=False),
    EnvVar('NEVERMINE_DISCORD_INVITE_URL', '', secret=False, production_required=False),
    EnvVar('NEVERMINE_API_BASE_URL', '', secret=False, production_required=False),
    EnvVar('NEVERMINE_API_TOKEN', '', secret=True, production_required=False),
    EnvVar('NEVERMINE_STATUS_ENDPOINT', '/status', secret=False, production_required=False),
    EnvVar('NEVERMINE_PLAYERS_ENDPOINT', '/players', secret=False, production_required=False),
    EnvVar('NEVERMINE_ANNOUNCEMENTS_ENDPOINT', '/community/announcements', secret=False, production_required=False),
    EnvVar('NEVERMINE_EVENTS_ENDPOINT', '/community/events', secret=False, production_required=False),
    EnvVar('NEVERMINE_VERIFY_START_ENDPOINT', '/community/verify/start', secret=False, production_required=False),
    EnvVar('NEVERMINE_VERIFY_COMPLETE_ENDPOINT', '/community/verify/complete', secret=False, production_required=False),
    EnvVar('NEVERMINE_LINK_STATUS_ENDPOINT', '/community/link/status', secret=False, production_required=False),
    EnvVar('NEVERMINE_LINK_UNLINK_ENDPOINT', '/community/link/unlink', secret=False, production_required=False),
    EnvVar('NEVERMINE_REQUEST_TIMEOUT', '8', secret=False, production_required=False),
    EnvVar('NEVERMINE_REQUEST_RETRIES', '3', secret=False, production_required=False),
    EnvVar('NEVERMINE_REQUEST_RETRY_BACKOFF_SECONDS', '1.0', secret=False, production_required=False),
    EnvVar('NEVERMINE_REQUEST_RETRY_BACKOFF_MAX_SECONDS', '8.0', secret=False, production_required=False),
    EnvVar('STAFF_ROLE_IDS', '', secret=False, production_required=False),
    EnvVar('ADMIN_USER_IDS', '', secret=False, production_required=False),
    EnvVar('VERIFIED_ROLE_ID', '', secret=False, production_required=False),
    EnvVar('MODERATION_ROLE_IDS', '', secret=False, production_required=False),
    EnvVar('SUPPORT_ROLE_IDS', '', secret=False, production_required=False),
    EnvVar('CONTENT_ROLE_IDS', '', secret=False, production_required=False),
    EnvVar('EVENT_ROLE_IDS', '', secret=False, production_required=False),
    EnvVar('COMMUNITY_MANAGER_ROLE_IDS', '', secret=False, production_required=False),
    EnvVar('STRICT_RUNTIME_PRECHECK', 'true', secret=False, production_required=False),
    EnvVar('RELAY_ENABLED', 'true', secret=False, production_required=False),
    EnvVar('RELAY_POLL_INTERVAL_SECONDS', '60', secret=False, production_required=False),
    EnvVar('RELAY_STATUS_CHANGES', 'true', secret=False, production_required=False),
    EnvVar('RELAY_ANNOUNCEMENTS', 'true', secret=False, production_required=False),
    EnvVar('RELAY_EVENTS', 'true', secret=False, production_required=False),
    EnvVar('STORAGE_BACKEND', 'sqlite', secret=False, production_required=False),
    EnvVar('DATABASE_URL', '', secret=True, production_required=False),
    EnvVar('SQLITE_PATH', '/app/data/nmdiscordbot.sqlite3', secret=False, production_required=False),
    EnvVar('POSTGRES_POOL_MIN_SIZE', '1', secret=False, production_required=False),
    EnvVar('POSTGRES_POOL_MAX_SIZE', '5', secret=False, production_required=False),
    EnvVar('REDIS_URL', '', secret=True, production_required=False),
    EnvVar('REDIS_NAMESPACE', 'nmdiscordbot', secret=False, production_required=False),
    EnvVar('REDIS_RELAY_DEDUPE_TTL_SECONDS', '604800', secret=False, production_required=False),
    EnvVar('REDIS_LOCK_TTL_SECONDS', '30', secret=False, production_required=False),
    EnvVar('REDIS_COMMAND_COOLDOWN_SECONDS', '5', secret=False, production_required=False),
    EnvVar('AUDIT_RELAY_MAX_PREVIEW_LENGTH', '320', secret=False, production_required=False),
    EnvVar('AUDIT_LOG_RETENTION_DAYS', '90', secret=False, production_required=False),
    EnvVar('VERIFICATION_SESSION_RETENTION_DAYS', '14', secret=False, production_required=False),
    EnvVar('RELAY_HISTORY_RETENTION_DAYS', '30', secret=False, production_required=False),
    EnvVar('CLEANUP_INTERVAL_SECONDS', '21600', secret=False, production_required=False),
    EnvVar('DATA_DIR', '/app/data', secret=False, production_required=False),
    EnvVar('SHARED_DIR', '/app/shared', secret=False, production_required=False),
    EnvVar('HEALTHCHECK_STRICT_STORAGE', 'true', secret=False, production_required=False),
    EnvVar('HEALTHCHECK_STRICT_REDIS', 'false', secret=False, production_required=False),
    EnvVar('COMMUNITY_CORE_EVENT_URL', '', secret=False, production_required=False),
    EnvVar('TELEGRAM_BRIDGE_URL', '', secret=False, production_required=False),
    EnvVar('VK_BRIDGE_URL', '', secret=False, production_required=False),
    EnvVar('WORKSPACE_BRIDGE_URL', '', secret=False, production_required=False),
    EnvVar('OUTBOUND_HMAC_SECRET', '', secret=True, production_required=False),
    EnvVar('OUTBOUND_BEARER_TOKEN', '', secret=True, production_required=False),
    EnvVar('OUTBOUND_KEY_ID', 'v1', secret=False, production_required=False),
    EnvVar('BRIDGE_TIMEOUT_SECONDS', '5', secret=False, production_required=False),
    EnvVar('BRIDGE_EVENT_TTL_SECONDS', '300', secret=False, production_required=False),
    EnvVar('BRIDGE_DELIVERY_BATCH_SIZE', '25', secret=False, production_required=False),
    EnvVar('INGRESS_ENABLED', 'false', secret=False, production_required=False),
    EnvVar('APP_PUBLIC_URL', '', secret=False, production_required=False),
    EnvVar('INGRESS_HOST', '0.0.0.0', secret=False, production_required=False),
    EnvVar('INGRESS_PORT', '8080', secret=False, production_required=False),
    EnvVar('PORT', '8080', secret=False, production_required=False),
    EnvVar('INGRESS_BEARER_TOKEN', '', secret=True, production_required=False),
    EnvVar('INGRESS_HMAC_SECRET', '', secret=True, production_required=False),
    EnvVar('INGRESS_STRICT_AUTH', 'true', secret=False, production_required=False),
    EnvVar('BRIDGE_SYNC_ANNOUNCEMENTS', 'true', secret=False, production_required=False),
    EnvVar('BRIDGE_SYNC_EVENTS', 'true', secret=False, production_required=False),
    EnvVar('BRIDGE_SYNC_SUPPORT', 'true', secret=False, production_required=False),
    EnvVar('BRIDGE_SYNC_REPORTS', 'true', secret=False, production_required=False),
    EnvVar('BRIDGE_SYNC_GUILD_RECRUITMENT', 'true', secret=False, production_required=False),
    EnvVar('BRIDGE_SYNC_IDENTITY', 'true', secret=False, production_required=False),
    EnvVar('APPROVAL_REQUIRED_FOR_ANNOUNCE', 'false', secret=False, production_required=False),
    EnvVar('APPROVAL_REQUIRED_FOR_VERIFY_UNLINK', 'false', secret=False, production_required=False),
    EnvVar('PANEL_AUTO_RECONCILE_ON_READY', 'true', secret=False, production_required=False),
    EnvVar('COMMUNITY_COMMAND_COOLDOWN_SECONDS', '20', secret=False, production_required=False),
    EnvVar('GUILD_RECRUIT_COMMAND_COOLDOWN_SECONDS', '120', secret=False, production_required=False),
    EnvVar('SCHEDULER_POLL_INTERVAL_SECONDS', '30', secret=False, production_required=False),
    EnvVar('FORUM_AUTO_CLOSE_INACTIVE_HOURS', '168', secret=False, production_required=False),
    EnvVar('FORUM_RECRUITMENT_AUTO_CLOSE_HOURS', '336', secret=False, production_required=False),
    EnvVar('FORUM_TAG_BUG_NAME', 'баг', secret=False, production_required=False),
    EnvVar('FORUM_TAG_SUPPORT_NAME', 'поддержка', secret=False, production_required=False),
    EnvVar('FORUM_TAG_SUGGESTION_NAME', 'предложение', secret=False, production_required=False),
    EnvVar('FORUM_TAG_APPEAL_NAME', 'апелляция', secret=False, production_required=False),
    EnvVar('FORUM_TAG_GUILD_RECRUITMENT_NAME', 'набор-в-гильдию', secret=False, production_required=False),
    EnvVar('FORUM_TAG_STATUS_OPEN_NAME', 'открыто', secret=False, production_required=False),
    EnvVar('FORUM_TAG_STATUS_IN_REVIEW_NAME', 'на-рассмотрении', secret=False, production_required=False),
    EnvVar('FORUM_TAG_STATUS_RESOLVED_NAME', 'решено', secret=False, production_required=False),
    EnvVar('FORUM_TAG_STATUS_CLOSED_NAME', 'закрыто', secret=False, production_required=False),
    EnvVar('DISCORD_CONTENT_FILE_PATH', './templates/content.json', secret=False, production_required=False),
    EnvVar('MIN_FREE_DISK_MB', '256', secret=False, production_required=False),
    EnvVar('LOG_DIR', '/app/data/logs', secret=False, production_required=False),
    EnvVar('RECOVERY_MODE_DEFAULT', 'false', secret=False, production_required=False),
    EnvVar('CONTENT_SCHEMA_VERSION_REQUIRED', '4', secret=False, production_required=False),
    EnvVar('BRIDGE_PAYLOAD_ALLOWLIST_JSON', '', secret=False, production_required=False),
    EnvVar('FORUM_AUTO_CREATE_TAGS', 'true', secret=False, production_required=False),
    EnvVar('RULES_VERSION', '1', secret=False, production_required=False),
    EnvVar('SUPPORT_ESCALATION_HOURS', '24', secret=False, production_required=False),
    EnvVar('APPEAL_ESCALATION_HOURS', '24', secret=False, production_required=False),
    EnvVar('REPORT_ESCALATION_HOURS', '12', secret=False, production_required=False),
    EnvVar('GUILD_RECRUITMENT_EXPIRY_WARNING_HOURS', '24', secret=False, production_required=False),
    EnvVar('FORUM_STATUS_SOURCE', 'hybrid', secret=False, production_required=False),
    EnvVar('DISCORD_CONTENT_REQUIRE_RUSSIAN', 'true', secret=False, production_required=False),
    EnvVar('INTEREST_ROLE_PING_MAP_JSON', '', secret=False, production_required=False),
    EnvVar('FORUM_DUPLICATE_DETECTION_HOURS', '72', secret=False, production_required=False),
    EnvVar('TOPIC_TRANSCRIPT_HISTORY_LIMIT', '200', secret=False, production_required=False),
    EnvVar('FORUM_POLICY_OVERRIDES_JSON', '{}', secret=False, production_required=False),
    EnvVar('MAINTENANCE_MODE_DEFAULT', 'false', secret=False, production_required=False),
    EnvVar('MAINTENANCE_MODE_MESSAGE', 'Сейчас включён режим технических работ. Создание новых тем временно недоступно. Попробуйте позже.', secret=False, production_required=False),
    EnvVar('INGRESS_PREVIOUS_HMAC_SECRET', '', secret=True, production_required=False),
    EnvVar('STAFF_SCOPE_ROLE_MAP_JSON', '{}', secret=False, production_required=False),
    EnvVar('STRICT_ENV_PRODUCTION_HYGIENE', 'true', secret=False, production_required=False),
    EnvVar('BACKUP_ON_CRITICAL_CHANGES', 'true', secret=False, production_required=False),
    EnvVar('BACKUP_DIR', '/app/data/backups', secret=False, production_required=False),
    EnvVar('BRIDGE_DLQ_AFTER_HOURS', '24', secret=False, production_required=False),
    EnvVar('JOB_DLQ_AFTER_HOURS', '24', secret=False, production_required=False),
    EnvVar('SYSTEMD_SERVICE_NAME', 'nmdiscordbot', secret=False, production_required=False),
    EnvVar('BRIDGE_EVENT_RULES_JSON', '', secret=False, production_required=False),
    EnvVar('LOG_LEVEL', 'INFO', secret=False, production_required=False),
    EnvVar('LOG_JSON', 'false', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_ENABLED', 'false', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_URL', 'https://logs.cajeer.ru/api/v1/ingest', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_TOKEN', '', secret=True, production_required=False),
    EnvVar('REMOTE_LOGS_PROJECT', 'NeverMine', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_BOT', 'NMDiscordBot', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_ENVIRONMENT', 'production', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_LEVEL', 'INFO', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_BATCH_SIZE', '25', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_FLUSH_INTERVAL', '5', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_TIMEOUT', '3', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_QUEUE_SIZE', '5000', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_MAX_SPOOL_FILES', '200', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_SPOOL_DIR', '/app/data/remote-logs-spool', secret=False, production_required=False),
    EnvVar('REMOTE_LOGS_SIGN_REQUESTS', 'false', secret=False, production_required=False),
    EnvVar('BOT_USE_PREFIX_COMMANDS', 'true', secret=False, production_required=False),
    EnvVar('COMMAND_PREFIX', '!', secret=False, production_required=False),
    EnvVar('COMMAND_SURFACE_MODE', 'compat', secret=False, production_required=False, description='compat/grouped-only/legacy-only'),
    EnvVar('METRICS_ENABLED', 'false', secret=False, production_required=False),
    EnvVar('METRICS_PATH', '/internal/metrics', secret=False, production_required=False),
    EnvVar('METRICS_REQUIRE_AUTH', 'true', secret=False, production_required=False),
    EnvVar('METRICS_BEARER_TOKEN', '', secret=True, production_required=False),
    EnvVar('METRICS_ALLOWED_IPS', '127.0.0.1,::1', secret=False, production_required=False),
    EnvVar('BRIDGE_MAX_ATTEMPTS', '8', secret=False, production_required=False),
    EnvVar('BRIDGE_RETRY_BACKOFF_BASE_SECONDS', '15', secret=False, production_required=False),
    EnvVar('BRIDGE_RETRY_BACKOFF_MAX_SECONDS', '900', secret=False, production_required=False),
    EnvVar('BRIDGE_DESTINATION_CIRCUIT_BREAKER_THRESHOLD', '5', secret=False, production_required=False),
    EnvVar('BRIDGE_DESTINATION_CIRCUIT_OPEN_SECONDS', '300', secret=False, production_required=False),
    EnvVar('SCHEDULER_MAX_ATTEMPTS', '5', secret=False, production_required=False),
    EnvVar('SCHEDULER_RETRY_BACKOFF_BASE_SECONDS', '30', secret=False, production_required=False),
    EnvVar('SCHEDULER_RETRY_BACKOFF_MAX_SECONDS', '1800', secret=False, production_required=False),
    EnvVar('DRIFT_MONITOR_ENABLED', 'true', secret=False, production_required=False),
    EnvVar('DRIFT_MONITOR_INTERVAL_SECONDS', '300', secret=False, production_required=False),
    EnvVar('DRIFT_ALERT_COOLDOWN_SECONDS', '1800', secret=False, production_required=False),
    EnvVar('LAYOUT_SCHEMA_VERSION_REQUIRED', '3', secret=False, production_required=False),
    EnvVar('ALIAS_BINDING_VERSION_REQUIRED', '1', secret=False, production_required=False),
    EnvVar('PERMISSION_MATRIX_VERSION_REQUIRED', '1', secret=False, production_required=False),
    EnvVar('MAX_TOPIC_ATTACHMENTS', '3', secret=False, production_required=False),
    EnvVar('ATTACHMENT_TOTAL_MAX_BYTES_DEFAULT', '20971520', secret=False, production_required=False),
    EnvVar('ATTACHMENT_MAX_BYTES_DEFAULT', '8388608', secret=False, production_required=False),
    EnvVar('ATTACHMENT_ALLOWED_EXTENSIONS_DEFAULT', 'png,jpg,jpeg,webp,gif,txt,log,json,pdf,zip,mp4,webm', secret=False, production_required=False),
    EnvVar('ATTACHMENT_BLOCKED_EXTENSIONS_DEFAULT', 'exe,bat,cmd,sh,ps1,msi,scr,jar', secret=False, production_required=False),
    EnvVar('FORUM_ATTACHMENT_POLICY_JSON', '{}', secret=False, production_required=False),
    EnvVar('RULES_REACCEPTANCE_ENFORCEMENT_ENABLED', 'true', secret=False, production_required=False),
    EnvVar('RULES_REACCEPTANCE_GRACE_HOURS', '72', secret=False, production_required=False),
    EnvVar('RULES_REACCEPTANCE_REMINDER_HOURS', '24', secret=False, production_required=False),
    EnvVar('RULES_REACCEPTANCE_CHECK_INTERVAL_SECONDS', '900', secret=False, production_required=False),
    EnvVar('TELEGRAM_EVENT_SEMANTIC_ALIASES_JSON', '', secret=False, production_required=False),
)

DEFAULTS: Final[dict[str, str]] = {item.name: item.default for item in ENV_SCHEMA}
SECRET_KEYS: Final[frozenset[str]] = frozenset(item.name for item in ENV_SCHEMA if item.secret)
PRODUCTION_REQUIRED_KEYS: Final[frozenset[str]] = frozenset(item.name for item in ENV_SCHEMA if item.production_required)


def env_default(name: str, fallback: str | None = None) -> str | None:
    return DEFAULTS.get(name, fallback)


def known_env_names() -> set[str]:
    return set(DEFAULTS)
